In [1]:
import pandas as pd
import numpy as np
import glob
from glob import iglob
import os

from dateutil import parser
from datetime import datetime
from dateutil.relativedelta import relativedelta

import mysql.connector
from sqlalchemy import create_engine
import pandas.io.sql as psql
from dateutil import parser
import sqlalchemy
from datetime import datetime

In [2]:
df = pd.read_csv("moneycontrol2012till2018.csv")
df

,Unnamed: 0,Call_Buy-Sell,Cmp_Name,Target_Price,Analyst_or_Cmp,Call_Time,Call_Time_normal,Call_Time_secs,Stop_Loss,From_Site
0,1,Buy,Cox and Kings,220.0,ICICI Direct,"November 23, 2018 03:06 PM",2018-11-23 03:06:00,"November 23, 2018 03:06 PM",NaN,MoneyControl
1,2,Buy,IG Petrochemicals,646.0,Nalanda Securities,"November 23, 2018 03:05 PM",2018-11-23 03:05:00,"November 23, 2018 03:05 PM",NaN,MoneyControl
2,3,Buy,Siyaram Silk Mills,460.0,ICICI Direct,"November 23, 2018 03:03 PM",2018-11-23 03:03:00,"November 23, 2018 03:03 PM",NaN,MoneyControl
3,4,Buy,JK Lakshmi Cement,315.0,ICICI Direct,"November 23, 2018 03:02 PM",2018-11-23 03:02:00,"November 23, 2018 03:02 PM",NaN,MoneyControl
4,5,Buy,Sunteck Realty,440.0,ICICI Direct,"November 23, 2018 02:54 PM",2018-11-23 02:54:00,"November 23, 2018 02:54 PM",NaN,MoneyControl
...,...,...,...,...,...,...,...,...,...,...
9069,9077,Buy,Maruti Suzuki India,1668.0,Motilal Oswal,"September 18, 2012 12:09 PM",2012-09-18 12:09:00,"September 18, 2012 12:09 PM",NaN,MoneyControl
9070,9078,Buy,Crompton Greaves,161.0,Microsec,"September 15, 2012 12:15 PM",2012-09-15 12:15:00,"September 15, 2012 12:15 PM",NaN,MoneyControl
9071,9079,Buy,Asian Paints,4250.0,Nirmal Bang,"September 14, 2012 02:36 PM",2012-09-14 02:36:00,"September 14, 2012 02:36 PM",NaN,MoneyControl
9072,9080,Buy,Eros International,188.0,Firstcall,"September 14, 2012 08:22 AM",2012-09-14 08:22:00,"September 14, 2012 08:22 AM",NaN,MoneyControl
9073,9081,Buy,M&M,850.0,Agarwal,"September 13, 2012 02:40 PM",2012-09-13 02:40:00,"September 13, 2012 02:40 PM",NaN,MoneyControl

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9074 entries, 0 to 9073
Data columns (total 10 columns):
Unnamed: 0          9074 non-null int64
Call_Buy-Sell       9074 non-null object
Cmp_Name            9074 non-null object
Target_Price        9074 non-null float64
Analyst_or_Cmp      9073 non-null object
Call_Time           9074 non-null object
Call_Time_normal    9074 non-null object
Call_Time_secs      9074 non-null object
Stop_Loss           0 non-null float64
From_Site           9074 non-null object
dtypes: float64(2), int64(1), object(7)
memory usage: 709.0+ KB

In [4]:
del df['Unnamed: 0']
del df[' PAID UP VALUE']
del df[' MARKET LOT']
del df[' FACE VALUE']
df

,SYMBOL,NAME OF COMPANY,SERIES,ISIN NUMBER
0,20MICRONS,20 Microns Limited,EQ,INE144J01027
1,21STCENMGM,21st Century Management Services Limited,EQ,INE253B01015
2,3IINFOTECH,3i Infotech Limited,EQ,INE748C01020
3,3MINDIA,3M India Limited,EQ,INE470A01017
4,3PLAND,3P Land Holdings Limited,EQ,INE105C01023
5,5PAISA,5Paisa Capital Limited,EQ,INE618L01018
6,63MOONS,63 moons technologies limited,EQ,INE111B01023
7,A2ZINFRA,A2Z Infra Engineering Limited,EQ,INE619I01012
8,AARTIDRUGS,Aarti Drugs Limited,EQ,INE767A01016
9,AARTIIND,Aarti Industries Limited,EQ,INE769A01020
10,AARVEEDEN,Aarvee Denims & Exports Limited,EQ,INE273D01019
11,AAVAS,Aavas Financiers Limited,EQ,INE216P01012
12,ABAN,Aban Offshore Limited,BE,INE421A01028
13,ABB,ABB India Limited,EQ,INE117A01022
14,ABBOTINDIA,Abbott India Limited,EQ,INE358A01014
15,ABCAPITAL,Aditya Birla Capital Limited,EQ,INE674K01013
16,ABFRL,Aditya Birla Fashion and Retail Limited,EQ,INE647O01011
17,ABMINTLTD,ABM International Limited,BE,INE251C01017
18,ACC,ACC Limited,EQ,INE012A01025
19,ACCELYA,Accelya Solutions India Limited,EQ,INE793A01012
20,ACE,Action Construction Equipment Limited,EQ,INE731H01025
21,ADANIENT,Adani Enterprises Limited,EQ,INE423A01024
22,ADANIGAS,Adani Gas Limited,EQ,INE399L01023
23,ADANIGREEN,Adani Green Energy Limited,EQ,INE364U01010
24,ADANIPORTS,Adani Ports and Special Economic Zone Limited,EQ,INE742F01042
25,ADANIPOWER,Adani Power Limited,EQ,INE814H01011
26,ADANITRANS,Adani Transmission Limited,EQ,INE931S01010
27,ADFFOODS,ADF Foods Limited,EQ,INE982B01019
28,ADHUNIK,Adhunik Metaliks Limited,BZ,INE400H01019
29,ADHUNIKIND,Adhunik Industries Limited,EQ,INE452L01012
...,...,...,...,...
1623,WHEELS,Wheels India Limited,EQ,INE715A01015
1624,WHIRLPOOL,Whirlpool of India Limited,EQ,INE716A01013
1625,WILLAMAGOR,Williamson Magor & Company Limited,EQ,INE210A01017
1626,WINDMACHIN,Windsor Machines Limited,BE,INE052A01021
1627,WINSOME,Winsome Yarns Limited,EQ,INE784B01035
1628,WIPL,The Western India Plywoods Limited,BE,INE215F01023
1629,WIPRO,Wipro Limited,EQ,INE075A01022
1630,WOCKPHARMA,Wockhardt Limited,EQ,INE049B01025
1631,WONDERLA,Wonderla Holidays Limited,EQ,INE066O01014
1632,WSI,W S Industries (I) Limited,BE,INE100D01014
1633,WSTCSTPAPR,West Coast Paper Mills Limited,EQ,INE976A01021
1634,XCHANGING,Xchanging Solutions Limited,EQ,INE692G01013
1635,XELPMOC,Xelpmoc Design And Tech Limited,EQ,INE01P501012
1636,XLENERGY,XL Energy Limited,BE,INE183H01011
1637,XPROINDIA,Xpro India Limited,EQ,INE445C01015
1638,YESBANK,Yes Bank Limited,EQ,INE528G01027
1639,ZEEL,Zee Entertainment Enterprises Limited,EQ,INE256A01028
1640,ZEELEARN,Zee Learn Limited,EQ,INE565L01011
1641,ZEEMEDIA,Zee Media Corporation Limited,EQ,INE966H01019
1642,ZENITHBIR,Zenith Birla (India) Limited,BE,INE318D01020
1643,ZENITHEXPO,Zenith Exports Limited,EQ,INE058B01018
1644,ZENSARTECH,Zensar Technologies Limited,EQ,INE520A01027
1645,ZENTEC,Zen Technologies Limited,EQ,INE251B01027
1646,ZICOM,Zicom Electronic Security Systems Limited,BE,INE871B01014
1647,ZODIACLOTH,Zodiac Clothing Company Limited,EQ,INE206B01013
1648,ZODJRDMKJ,Zodiac JRD- MKJ Limited,EQ,INE077B01018
1649,ZOTA,Zota Health Care LImited,EQ,INE358U01012
1650,ZUARI,Zuari Agro Chemicals Limited,EQ,INE840M01016
1651,ZUARIGLOB,Zuari Global Limited,EQ,INE217A01012
1652,ZYDUSWELL,Zydus Wellness Limited,EQ,INE768C01010

In [5]:
database_username = 'root'
database_password = 'yash'
database_ip       = '127.0.0.1'
database_name     = 'mainschema'
database_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name))

In [6]:
df.to_sql(con=database_connection, name='symbols', if_exists='append')