In [1]:
import pandas as pd
import numpy as np

import mysql.connector
from sqlalchemy import create_engine
import pandas.io.sql as psql
import sqlalchemy

from dateutil import parser
from datetime import datetime
from datetime import date
from dateutil.relativedelta import relativedelta

In [2]:
database_username = 'root'
database_password = 'yash'
database_ip       = '127.0.0.1'
database_name     = 'mainschema'
database_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name))

In [3]:
df = pd.read_sql('SELECT * FROM marketsmojorecos', con=database_connection)

In [4]:
start_date = '2016-01-01'
end_date = '2016-12-31'
date_object1 = datetime.strptime(start_date, '%Y-%m-%d').date()
date_object2 = datetime.strptime(end_date, '%Y-%m-%d').date()

In [5]:
mask = (df['predict_date'] > date_object1) & (df['predict_date'] <= date_object2)

# 2016 data

In [6]:
df1 = df.loc[mask]
df1 = df1.reset_index()
del df1['level_0']
del df1['srno']
del df1['index']

In [7]:
print("No of Brokers in 2016 :",df1['broker'].nunique()) 
s1=len(df1)

No of Brokers in 2016 : 61

In [8]:
df3=pd.DataFrame()
for i in range(0,5198): 
    sym=df1.at[i, 'company_name']
    sym = sym.lower()
    sym = sym.replace(" ","")
    sym = sym.replace(".","")
    sym = sym.replace("(i)","")
    sym = sym.replace("(","")
    sym = sym.replace(")","")
    sym = sym.replace("-","")
    sqlrun = "SELECT SYMBOL FROM symbolsmapped WHERE recoName = '"+sym+"'"
    df3 = df3.append(pd.read_sql(sqlrun, con=database_connection),ignore_index=True)

In [9]:
df4 =pd.concat([df1,df3],axis=1)
df4

,broker,company_name,current_price,recomended_buying,predict_date,target_price,SYMBOL
0,KRChoksey,Force Motors,1199.90,3497.00,2016-10-03,4820.00,FORCEMOT
1,AUM Capital,Narayana Hrudayalay,239.00,325.55,2016-09-27,400.00,NH
2,Religare,ICICI Bank,390.15,217.73,2016-08-04,181.82,ICICIBANK
3,Enochventures.com,Parag Milk Foods,137.65,329.6,2016-07-12,425.00,PARAGMILK
4,Edelweiss,Kewal Kiran Clothing,1000.00,1796.00,2016-05-25,2039.00,KKCL
...,...,...,...,...,...,...,...
5193,Axis Direct,Cox & Kings India,3.61,179.00,2016-04-06,338.00,CKFSL
5194,Dolat Capital,Mphasis,966.20,454.00,2016-04-05,620.00,MPHASIS
5195,Angel Broking,Dewan Hsg Fin. Corp.,47.15,189.00,2016-04-05,270.00,DHFL
5196,Angel Broking,MBL Infrastructures,5.57,154.00,2016-04-04,285.00,MBLINFRA
5197,ICICIdirect.com,Ultratech Cem,3883.75,3237.00,2016-04-01,3600.00,ULTRACEMCO

In [11]:
uniqueBrokers = df4.broker.unique()
uniqueBrokers

array(['KRChoksey', 'AUM Capital', 'Religare', 'Enochventures.com',
       'Edelweiss', 'Motilal Oswal', 'Kotak Securities', 'Angel Broking',
       'Geojit Financial Services', 'Centrum', 'IIFL', 'ICICIdirect.com',
       'Axis Direct', 'Moneylicious', 'CD Equisearch', 'Nirmal Bang',
       'Arihant Capital Markets', 'Prabhudas Lilladher',
       'Wallfort Financial', 'HDFC Securities', 'BP Wealth',
       'Rudra Shares & Stocks Brokers', 'GEPL Capital', 'Dynamic Levels',
       'Choice Equity Broking', 'Right Horizons',
       'Systematix Shares & Stocks', 'East India Securities Ltd',
       'Sethi Finmart', 'Maximus Securities', 'Ajcon Global',
       'India Nivesh', 'Way2Wealth', 'YES Securities', 'AnandRathi',
       'SPA Securities', 'Khambatta Securities', 'Reliance Securities',
       'Dolat Capital', 'LKP Securities Limited',
       'Cholamandalam Securities', 'JM Financial', 'Ashika Stock Broking',
       'Antique Stock Broking', 'Karvy Stock Broking',
       'Blue Ocean Strategic Advisors', 'Sharekhan',
       'Precision Technicals', 'Investment Imperative',
       'Avinash Gorakshakar - Market Expert', 'Hem Securities',
       'Powermywealth.com', 'Shahina Mukadam',
       'Equinomics Research & Advisory Pvt. Ltd', 'Prakashgaba.com',
       'Asian Market Securities', 'Elara Capital', 'SMC Research',
       'Prakashdiwan.in', 'FortuneWizard.com', 'Phillip Capital'],
      dtype=object)

In [13]:
del brokerPerformace
brokerPerformace = pd.DataFrame(columns=['Name','Hit Ratio','Avg. Growth','Total Recos'])
brokerPerformace

Empty DataFrame
Columns: [Name, Hit Ratio, Avg. Growth, Total Recos]
Index: []

In [20]:
for brokerName in uniqueBrokers :
    dfbrokerRecos = df4.loc[df4['broker'] == brokerName]
    #print('brokerName : ',brokerName)
    hits=0
    growthSum=0
    total=0
    for index, row in dfbrokerRecos.iterrows():
        #print(row)
        #sym = row['SYMBOL']
        #print(type(sym))
        if type(sym) == str :
            mydate1 = row['predict_date']#prediction date
            mydate2 = mydate1 + relativedelta(years=1)#date 1 year after prediction
            dbyear1 = "nse"+str(mydate1.year)
            dbyear2 = "nse"+str(mydate2.year)
        
            sqlrun1 = "SELECT * FROM "+dbyear1+" WHERE Date >= '"+str(mydate1)+"' AND Symbol = '"+sym+"'"
            dfprices1 = pd.read_sql(sqlrun1, con=database_connection)
            del dfprices1['index']
        
            sqlrun2 = "SELECT * FROM "+dbyear2+" WHERE Date <= '"+str(mydate2)+"' AND Symbol = '"+sym+"'"
            dfprices2 = pd.read_sql(sqlrun2, con=database_connection)
            del dfprices2['index']
            dfprices = pd.concat([dfprices1,dfprices2],ignore_index=True)

            targetp = float(row['target_price'])
        
            #print("SYMBOL : ",sym)
            dfhits = dfprices.loc[dfprices['Closeval'] >= targetp]
            
            total = total + 1
            
            if not dfhits.empty :
                #print("HIT!")
                hits = hits + 1
                recbuying = float(row['recomended_buying'])
                maxval = dfprices['Closeval'].max()
                growthperc = (maxval - recbuying) *100 / recbuying
                #print('Growth : ',growthperc)
                if np.isnan(growthperc):
                    total = total-1
                else:    
                    growthSum = growthSum + growthperc
            #else:
                #print("DIDN'T HIT!")
    if total != 0:
        hitRatio = int(hits*100 / total)
        avgGrowth = int(growthSum / total)
        print("Broker : ", brokerName, "HitRatio : ", hitRatio, "Avg. Growth : ", avgGrowth, "Total Recos. : ", total)
        brokerPerformace = brokerPerformace.append({'Name':brokerName,'Hit Ratio':hitRatio,'Avg. Growth':avgGrowth,'Total Recos':total}, ignore_index=True)

Broker :  KRChoksey HitRatio :  87 Avg. Growth :  716 Total Recos. :  217
Broker :  AUM Capital HitRatio :  100 Avg. Growth :  777 Total Recos. :  21
Broker :  Religare HitRatio :  90 Avg. Growth :  478 Total Recos. :  365
Broker :  Enochventures.com HitRatio :  100 Avg. Growth :  960 Total Recos. :  30
Broker :  Edelweiss HitRatio :  93 Avg. Growth :  886 Total Recos. :  487
Broker :  Motilal Oswal HitRatio :  92 Avg. Growth :  838 Total Recos. :  515
Broker :  Kotak Securities HitRatio :  84 Avg. Growth :  1520 Total Recos. :  132
Broker :  Angel Broking HitRatio :  100 Avg. Growth :  707 Total Recos. :  111
Broker :  Geojit Financial Services HitRatio :  94 Avg. Growth :  913 Total Recos. :  208
Broker :  Centrum HitRatio :  93 Avg. Growth :  850 Total Recos. :  248
Broker :  IIFL HitRatio :  89 Avg. Growth :  1530 Total Recos. :  57
Broker :  ICICIdirect.com HitRatio :  88 Avg. Growth :  714 Total Recos. :  767
Broker :  Axis Direct HitRatio :  93 Avg. Growth :  603 Total Recos. :  495
Broker :  Moneylicious HitRatio :  100 Avg. Growth :  894 Total Recos. :  30
Broker :  CD Equisearch HitRatio :  95 Avg. Growth :  687 Total Recos. :  65
Broker :  Nirmal Bang HitRatio :  82 Avg. Growth :  399 Total Recos. :  90
Broker :  Arihant Capital Markets HitRatio :  81 Avg. Growth :  571 Total Recos. :  85
Broker :  Prabhudas Lilladher HitRatio :  89 Avg. Growth :  785 Total Recos. :  317
Broker :  Wallfort Financial HitRatio :  100 Avg. Growth :  4000 Total Recos. :  3
Broker :  HDFC Securities HitRatio :  95 Avg. Growth :  1803 Total Recos. :  60
Broker :  BP Wealth HitRatio :  100 Avg. Growth :  775 Total Recos. :  3
Broker :  Rudra Shares & Stocks Brokers HitRatio :  100 Avg. Growth :  1114 Total Recos. :  9
Broker :  GEPL Capital HitRatio :  100 Avg. Growth :  747 Total Recos. :  12
Broker :  Dynamic Levels HitRatio :  91 Avg. Growth :  1238 Total Recos. :  106
Broker :  Choice Equity Broking HitRatio :  100 Avg. Growth :  139 Total Recos. :  3
Broker :  Right Horizons HitRatio :  60 Avg. Growth :  626 Total Recos. :  15
Broker :  Systematix Shares & Stocks HitRatio :  100 Avg. Growth :  266 Total Recos. :  15
Broker :  East India Securities Ltd HitRatio :  100 Avg. Growth :  1426 Total Recos. :  26
Broker :  Sethi Finmart HitRatio :  100 Avg. Growth :  765 Total Recos. :  18
Broker :  Maximus Securities HitRatio :  100 Avg. Growth :  1575 Total Recos. :  3
Broker :  Ajcon Global HitRatio :  100 Avg. Growth :  846 Total Recos. :  15
Broker :  India Nivesh HitRatio :  100 Avg. Growth :  750 Total Recos. :  14
Broker :  Way2Wealth HitRatio :  86 Avg. Growth :  1604 Total Recos. :  36
Broker :  YES Securities HitRatio :  100 Avg. Growth :  904 Total Recos. :  36
Broker :  AnandRathi HitRatio :  92 Avg. Growth :  414 Total Recos. :  41
Broker :  SPA Securities HitRatio :  100 Avg. Growth :  1650 Total Recos. :  92
Broker :  Khambatta Securities HitRatio :  92 Avg. Growth :  584 Total Recos. :  28
Broker :  Reliance Securities HitRatio :  86 Avg. Growth :  572 Total Recos. :  147
Broker :  Dolat Capital HitRatio :  100 Avg. Growth :  331 Total Recos. :  56
Broker :  LKP Securities Limited HitRatio :  100 Avg. Growth :  297 Total Recos. :  6
Broker :  Cholamandalam Securities HitRatio :  100 Avg. Growth :  87 Total Recos. :  3
Broker :  JM Financial HitRatio :  91 Avg. Growth :  611 Total Recos. :  48
Broker :  Ashika Stock Broking HitRatio :  100 Avg. Growth :  35 Total Recos. :  3
Broker :  Antique Stock Broking HitRatio :  100 Avg. Growth :  407 Total Recos. :  6
Broker :  Karvy Stock Broking HitRatio :  78 Avg. Growth :  1302 Total Recos. :  23
Broker :  Blue Ocean Strategic Advisors HitRatio :  100 Avg. Growth :  796 Total Recos. :  9
Broker :  Sharekhan HitRatio :  100 Avg. Growth :  579 Total Recos. :  21
Broker :  Precision Technicals HitRatio :  100 Avg. Growth :  456 Total Recos. :  9
Broker :  Investment Imperative HitRatio :  100 Avg. Growth :  338 Total Recos. :  3
Broker :  Avinash Gorakshakar - Market Expert HitRatio :  100 Avg. Growth :  266 Total Recos. :  3
Broker :  Hem Securities HitRatio :  100 Avg. Growth :  88 Total Recos. :  3
Broker :  Powermywealth.com HitRatio :  100 Avg. Growth :  1633 Total Recos. :  36
Broker :  Shahina Mukadam HitRatio :  100 Avg. Growth :  484 Total Recos. :  14
Broker :  Equinomics Research & Advisory Pvt. Ltd HitRatio :  100 Avg. Growth :  3622 Total Recos. :  3
Broker :  Prakashgaba.com HitRatio :  100 Avg. Growth :  670 Total Recos. :  5
Broker :  Asian Market Securities HitRatio :  100 Avg. Growth :  1562 Total Recos. :  6
Broker :  Elara Capital HitRatio :  100 Avg. Growth :  822 Total Recos. :  3
Broker :  SMC Research HitRatio :  100 Avg. Growth :  799 Total Recos. :  10
Broker :  Prakashdiwan.in HitRatio :  100 Avg. Growth :  138 Total Recos. :  2
Broker :  FortuneWizard.com HitRatio :  100 Avg. Growth :  271 Total Recos. :  2
Broker :  Phillip Capital HitRatio :  100 Avg. Growth :  312 Total Recos. :  2

In [21]:
brokerPerformace

                 Name Hit Ratio Avg. Growth Total Recos
0           KRChoksey       100         113         145
1         AUM Capital       100          91          15
2            Religare       100          73         291
3   Enochventures.com       100          68          13
4           Edelweiss       100         190         360
..                ...       ...         ...         ...
66      Elara Capital       100         822           3
67       SMC Research       100         799          10
68    Prakashdiwan.in       100         138           2
69  FortuneWizard.com       100         271           2
70    Phillip Capital       100         312           2

[71 rows x 4 columns]

In [22]:
brokerPerformace.to_sql(con=database_connection, name='brokerperformance2016', if_exists='replace')